config/routes.rb
Rails.application.routes.draw do
  draw(:active_storage)
  mount ActionCable.server => '/cable'

  devise_for :admin_users
  devise_for :buyers, controllers: {confirmations: 'buyers/confirmations', registrations: 'buyers/registrations'}

  namespace :admin do
    resources :admin_users
    resources :buyers, only: [:index, :show]
    resources :deliveries, only: [:show]
    resources :district_profiles, only: [:index, :show, :edit, :update]
    resources :locations, only: [:show]
    resources :procurement_types, only: [:index, :show, :new, :create, :edit, :update]
    resources :procurement_type_score_categories, only: [:show, :edit, :update, :destroy]
    resources :rfps, only: [:index, :show, :edit, :update] do
      get :download
    end

    resources :score_categories, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :score_presets, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :score_preset_values, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :scores, only: [:edit, :update, :show]

    delete :rfp_item_list_destroy, to: 'rfps#destroy_item_list'
    delete :rfp_draft_destroy, to: 'rfps#destroy_draft'
    delete :rfp_reviewed_destroy, to: 'rfps#destroy_reviewed'
    delete :rfp_final_destroy, to: 'rfps#destroy_final'

    root to: 'buyers#index'
  end

  namespace :buyers do
    resource :district_profile, only: [:show, :edit, :update, :destroy] do
      scope module: :district_profiles do
        resource :contact, only: [:edit, :update]
        resource :procurement, only: [:edit, :update]
        resources :locations, only: [:index, :show, :create, :new, :edit, :update, :destroy]
      end
    end
    resources :documents, only: [:index]
    resources :rfps, except: [:index] do
      resources :scores, except: [:new, :edit, :destroy]
      resources :score_presets, only: [:show, :update]
      resources :deliveries
      resource :item_list, only: [:edit, :update]
      resource :draft, only: [:create]
      resource :download, only: [:show]
      resource :reviewed, only: [:update]
      resource :final, only: [:update]
    end
    resource :resources, only: [:show]
    root to: 'documents#index'
  end

  resource :terms, only: [:show]

  root to: 'buyers/documents#index'
end

app/controllers/admin/buyers_controller.rb
class Admin::BuyersController < Admin::ApplicationController
  def scoped_resource
    Buyer.where.not(confirmed_at: nil)
  end
end

app/controllers/admin/district_profiles_controller.rb
class Admin::DistrictProfilesController < Admin::ApplicationController
end

app/controllers/buyers/application_controller.rb
class Buyers::ApplicationController < ApplicationController
  include Pundit::Authorization

  before_action :authenticate_buyer!, unless: :devise_controller?
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def pundit_user = current_buyer

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(request.referer || root_path)
  end
end

app/controllers/buyers/confirmations_controller.rb
class Buyers::ConfirmationsController < Devise::ConfirmationsController
  def show
    super do |buyer|
      AdminNotificationMailer.new_registration(resource).deliver if buyer.confirmed?
    end
  end
end

app/controllers/buyers/deliveries_controller.rb
class Buyers::DeliveriesController < Buyers::ApplicationController
  after_action :verify_authorized

  def index
    authorize(current_rfp, :edit?)
    @rfp = current_rfp
  end

  def new
    authorize(current_rfp, :edit?)
    @delivery = current_rfp.deliveries.build(window_start_time: 4, window_end_time: 5)
  end

  def edit
    authorize(current_rfp, :edit?)
    @delivery = current_rfp.deliveries.find(params[:id])
  end

  def create
    authorize(current_rfp, :edit?)
    @delivery = current_rfp.deliveries.build(delivery_params)
    respond_to do |format|
      if @delivery.save
        format.any do
          flash[:success] = 'Schedule was successfully created.'
          redirect_to buyers_rfp_deliveries_path(current_rfp), status: :see_other
        end
      else
        flash.now[:alert] = 'Schedule could not be saved.'
        format.html { render :new }
        format.turbo_stream { render :create }
      end
    end
  end

  def update
    authorize(current_rfp, :edit?)
    @delivery = current_rfp.deliveries.find(params[:id])
    respond_to do |format|
      if @delivery.update(delivery_params)
        format.any do
          flash[:success] = 'Schedule was successfully updated.'
          redirect_to buyers_rfp_deliveries_path(current_rfp), status: :see_other
        end
      else
        flash.now[:alert] = 'Schedule could not be saved.'
        format.html { render :edit }
        format.turbo_stream { render :update }
      end
    end
  end

  def destroy
    authorize(current_rfp, :edit?)
    schedule = current_rfp.deliveries.find(params[:id])
    schedule.destroy
    redirect_to buyers_rfp_deliveries_path(current_rfp)
  end

  private

  def delivery_params
    unprocessed_params.merge(delivery_days: unprocessed_params.fetch(:delivery_days, []).reject(&:blank?))
  end

  def unprocessed_params
    params.require(:delivery).permit(:location_id, :deliveries_per_week, :window_start_time, :window_end_time, delivery_days: [])
  end

  def current_rfp
    @current_rfp ||= Rfp.find(params[:rfp_id])
  end
end

app/controllers/buyers/district_profiles/contacts_controller.rb
class Buyers::DistrictProfiles::ContactsController < Buyers::ApplicationController
  before_action -> { redirect_to edit_buyers_district_profile_path }, unless: -> { current_buyer.district_profile.present? }

  def edit
    @district_profile = current_buyer.district_profile
  end

  def update
    @district_profile = current_buyer.district_profile
    respond_to do |format|
      if @district_profile.update(district_profile_params)
        if params.key?(:draft)
          @district_profile.valid?(:rfp_contact)
          flash.now[:success] = 'District Profile was successfully updated.'
          format.html { render :edit }
          format.turbo_stream { render :update }
        else
          format.any do
            flash[:success] = 'District Profile was successfully updated.'
            redirect_to edit_buyers_district_profile_procurement_path, status: :see_other
          end
        end
      else
        flash.now[:alert] = 'District Profile could not be saved.'
        format.html { render :edit }
        format.turbo_stream { render :update }
      end
    end
  end

  private

  def district_profile_params
    params.require(:district_profile).permit(:contact_full_name, :contact_mailing_address_city, :contact_department_name, :contact_full_name, :contact_mailing_address_state, :contact_mailing_address_street, :contact_mailing_address_zip, :contact_phone_number, :contact_title)
  end
end

app/controllers/buyers/district_profiles/locations_controller.rb
class Buyers::DistrictProfiles::LocationsController < Buyers::ApplicationController
  before_action -> { redirect_to edit_buyers_district_profile_path }, unless: -> { current_buyer.district_profile.present? }
  after_action :verify_authorized, except: [:index, :new, :create]

  def index
    @district_profile = current_buyer.district_profile
  end

  def new
    @location = current_buyer.locations.build
  end

  def create
    @location = current_buyer.locations.build(location_params)
    respond_to do |format|
      if @location.save
        format.any do
          flash[:success] = 'Location was successfully created.'
          redirect_to buyers_district_profile_locations_path, status: :see_other
        end
      else
        flash.now[:alert] = 'Location could not be saved.'
        format.html { render :new }
        format.turbo_stream { render :create }
      end
    end
  end

  def edit
    @location = Location.find(params[:id])
    authorize(@location)
  end

  def update
    @location = Location.find(params[:id])
    authorize(@location)
    @location.assign_attributes(location_params)
    respond_to do |format|
      if @location.save
        format.any do
          flash[:success] = 'Location was successfully updated.'
          redirect_to buyers_district_profile_locations_path, status: :see_other
        end
      else
        flash.now[:alert] = 'Location could not be saved.'
        format.html { render :edit }
        format.turbo_stream { render :update }
      end
    end
  end

  def destroy
    location = Location.find(params[:id])
    authorize(location)
    location.destroy
    redirect_to buyers_district_profile_locations_path
  end

  private

  def location_params
    params.require(:location).permit(:name, :street_address, :city, :state, :zip_code)
  end
end

app/controllers/buyers/district_profiles/procurements_controller.rb
class Buyers::DistrictProfiles::ProcurementsController < Buyers::ApplicationController
  before_action -> { redirect_to edit_buyers_district_profile_path }, unless: -> { current_buyer.district_profile.present? }

  def edit
    @district_profile = current_buyer.district_profile
  end

  def update
    @district_profile = current_buyer.district_profile
    respond_to do |format|
      if @district_profile.update(district_profile_params)
        if params.key?(:draft)
          @district_profile.valid?(:procurement_terms)
          flash.now[:success] = 'District Profile was successfully updated.'
          format.html { render :edit }
          format.turbo_stream { render :update }
        else
          format.any do
            flash[:success] = 'District Profile was successfully updated.'
            redirect_to buyers_district_profile_locations_path, status: :see_other
          end
        end
      else
        flash.now[:alert] = 'District Profile could not be saved.'
        format.html { render :edit }
        format.turbo_stream { render :update }
      end
    end
  end

  private

  def district_profile_params
    params.require(:district_profile).permit(:local_percentage, :price_verified, :allow_piggyback, :required_insurance_aggregate, :required_insurance_automobile, :required_insurance_per_incident)
  end
end

app/controllers/buyers/district_profiles_controller.rb
class Buyers::DistrictProfilesController < Buyers::ApplicationController
  before_action -> { redirect_to edit_buyers_district_profile_path }, if: -> { current_buyer.district_profile.blank? }, only: [:show]

  def show
    @district_profile = current_buyer.district_profile || current_buyer.build_district_profile
  end

  def edit
    @district_profile = current_buyer.district_profile || current_buyer.build_district_profile
  end

  def update
    @district_profile = current_buyer.district_profile || current_buyer.build_district_profile
    respond_to do |format|
      if @district_profile.update(district_profile_params)
        if params.key?(:draft)
          @district_profile.valid?(:district_information)
          format.html { render :edit }
          format.turbo_stream { render :update }
        else
          format.any do
            flash[:success] = 'District Profile was successfully updated.'
            redirect_to edit_buyers_district_profile_contact_path, status: :see_other
          end
        end
      else
        flash[:alert] = 'District Profile could not be saved.'
        format.html { render :edit }
        format.turbo_stream { render :update }
      end
    end
  end

  private

  def district_profile_params
    params.require(:district_profile).permit(:district_name, :city, :county, :enrolled_students_number)
  end
end

app/controllers/buyers/documents_controller.rb
class Buyers::DocumentsController < Buyers::ApplicationController
  def index
    flash.now[:warning] = t('.complete_your_profile_html', complete_link: view_context.link_to(t('.complete_link_html'), edit_buyers_district_profile_path, class: 'flash__link')).html_safe unless current_buyer.district_profile&.complete?
    @documents = current_buyer.rfps.order(updated_at: :desc).page(params[:page] || 1).per(params[:per_page] || Kaminari.config.default_per_page)
  end
end

app/controllers/buyers/downloads_controller.rb
class Buyers::DownloadsController < Buyers::ApplicationController
  after_action :verify_authorized

  def show
    authorize(current_rfp)
    ::RfpCompositor.new(current_rfp).create do |download|
      send_data download.read, filename: "DRAFT_RFP_#{Time.current.to_fs(:number)}.docx"
    end
  end

  private

  def current_rfp
    @current_rfp ||= Rfp.find(params[:rfp_id])
  end
end

app/controllers/buyers/drafts_controller.rb
class Buyers::DraftsController < Buyers::ApplicationController
  after_action :verify_authorized

  def create
    authorize(current_rfp)
    if ::RfpCompositor.new(current_rfp).attach
      flash[:success] = 'Draft RFP was successfully created.'
    else
      flash[:alert] = 'There was a problem creating the RFP.'
    end
    redirect_to buyers_rfp_path(current_rfp)
  end

  private

  def current_rfp
    @current_rfp ||= Rfp.find(params[:rfp_id])
  end
end

app/controllers/buyers/finals_controller.rb
class Buyers::FinalsController < Buyers::ApplicationController
  after_action :verify_authorized

  def update
    @rfp ||= Rfp.find(params[:rfp_id])
    authorize(@rfp)
    @rfp.final.attach(item_list_params[:final])
    redirect_to buyers_rfp_path(@rfp)
  end

  private

  def item_list_params
    params.require(:rfp).permit(:final)
  end
end

app/controllers/buyers/item_lists_controller.rb
class Buyers::ItemListsController < Buyers::ApplicationController
  after_action :verify_authorized

  def edit
    @rfp = Rfp.find(params[:rfp_id])
    authorize(@rfp)
  end

  def update
    @rfp = Rfp.find(params[:rfp_id])
    authorize(@rfp)
    respond_to do |format|
      if @rfp.item_list.attach(item_list_params[:item_list])
        flash.now[:success] = 'District Profile was successfully updated.'
      else
        flash.now[:alert] = 'District Profile could not be saved.'
      end
      format.html { render :edit }
      format.turbo_stream { render :update }
    end
  end

  private

  def item_list_params
    params.require(:rfp).permit(:item_list)
  end
end

app/controllers/buyers/registrations_controller.rb
class Buyers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:full_name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:full_name, :email, :password, :current_password)
    end
  end

  def after_sign_up_path_for(_resource)
    new_buyer_session_path if is_navigational_format?
  end

  def after_inactive_sign_up_path_for(_resource)
    new_buyer_session_path
  end
end

app/controllers/buyers/resources_controller.rb
class Buyers::ResourcesController < Buyers::ApplicationController
  skip_before_action :authenticate_buyer!

  def show
    redirect_to Rails.application.config.external_resources_link, allow_other_host: true
  end
end

app/controllers/buyers/revieweds_controller.rb
class Buyers::ReviewedsController < Buyers::ApplicationController
  after_action :verify_authorized

  def update
    @rfp ||= Rfp.find(params[:rfp_id])
    authorize(@rfp)
    @rfp.reviewed.attach(item_list_params[:reviewed])
    redirect_to buyers_rfp_path(@rfp)
  end

  private

  def item_list_params
    params.require(:rfp).permit(:reviewed)
  end
end

app/controllers/buyers/rfps_controller.rb
class Buyers::RfpsController < Buyers::ApplicationController
  after_action :verify_authorized, except: [:new, :create]

  def new
    @rfp = current_buyer.rfps.build(start_year: Time.current.year)
  end

  def create
    @rfp = current_buyer.rfps.build(rfp_params)
    respond_to do |format|
      if @rfp.save
        if params.key?(:draft)
          format.any do
            flash[:success] = 'New RFP was created.'
            redirect_to edit_buyers_rfp_path(@rfp), status: :see_other
          end
        else
          format.any do
            flash[:success] = 'RFP was successfully updated.'
            redirect_to buyers_rfp_scores_path(@rfp), status: :see_other
          end
        end
      else
        flash[:alert] = 'RFP could not be saved.'
        format.html { render :new }
        format.turbo_stream { render :create }
      end
    end
  end

  def show
    @rfp = Rfp.find(params[:id])
    authorize(@rfp)
    @rfp.complete?
  end

  def edit
    @rfp = Rfp.find(params[:id])
    authorize(@rfp)
  end

  def update
    @rfp = Rfp.find(params[:id])
    authorize(@rfp)
    @rfp.assign_attributes(rfp_params)
    respond_to do |format|
      if @rfp.save
        if params.key?(:draft)
          flash.now[:success] = 'RFP was successfully updated.'
          format.html { render :edit }
          format.turbo_stream { render :update }
        else
          format.any do
            flash[:success] = 'RFP was successfully updated.'
            redirect_to buyers_rfp_scores_path(@rfp), status: :see_other
          end
        end
      else
        flash.now[:alert] = 'RFP could not be saved.'
        format.html { render :edit }
        format.turbo_stream { render :update }
      end
    end
  end

  def destroy
    @rfp = Rfp.find(params[:id])
    authorize(@rfp)
    if @rfp.destroy
      flash[:notice] = 'RFP was deleted.'
    else
      flash[:alert] = 'RFP could not be deleted.'
    end
    redirect_to buyers_documents_path
  end

  private

  def rfp_params
    params.require(:rfp).permit(:procurement_type_id, :start_year)
  end
end

app/views/buyers/district_profiles/_form.html.erb
<%= turbo_frame_tag 'buyers-district-profile' do %>
  <%= form_for district_profile, as: :district_profile, url: buyers_district_profile_url, method: :patch, html: {data: {turbo_frame: '_top'}} do |f| %>
    <div class="divide-y divide-gray-200">
      <div class="grid grid-cols-1 gap-y-4 gap-x-4 sm:grid-cols-6">
        <div class="sm:col-span-6">
          <%= f.label :district_name %>
          <%= f.text_field :district_name, required: true %>
        </div>

        <div class="sm:col-span-3">
          <%= f.label :city %>
          <%= f.text_field :city %>
        </div>

        <div class="sm:col-span-3">
          <%= f.label :county %>
          <%= f.text_field :county %>
        </div>

        <div class="sm:col-span-3">
          <%= f.label :enrolled_students_number %>
          <%= f.number_field :enrolled_students_number %>
        </div>
      </div>

      <div class="pt-4 mt-4">
        <div class="flex justify-start space-x-4">
          <%= f.button 'Next', class: 'forms-submit' %>
          <%= f.button 'Save draft', class: 'forms-submit--outline', name: :draft, value: true %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/buyers/district_profiles/edit.html.erb
<div class="divide-y divide-gray-200">
  <div class="space-y-8">
    <%= render(Buyers::Steps::Component.new(title: DistrictProfile.model_name.human)) do |component| %>
      <%= component.step index: 1, current_index: 1, section: t(:district_information, scope: [:activerecord, :attributes, :district_profile]), path: edit_buyers_district_profile_path, valid: @district_profile.valid?(:district_information) %>
      <%= component.step index: 2, current_index: 1, section: t(:rfp_contact, scope: [:activerecord, :attributes, :district_profile]), path: edit_buyers_district_profile_contact_path, valid: @district_profile.valid?(:rfp_contact) %>
      <%= component.step index: 3, current_index: 1, section: t(:procurement_terms, scope: [:activerecord, :attributes, :district_profile]), path: edit_buyers_district_profile_procurement_path, valid: @district_profile.valid?(:procurement_terms) %>
      <%= component.step index: 4, current_index: 1, section: t(:locations, scope: [:activerecord, :attributes, :district_profile]), path: buyers_district_profile_locations_path, valid: @district_profile.valid?(:locations) %>
    <% end %>

    <div>
      <h2 class="text-lg leading-6 font-medium text-gray-900"><%= t('.title') %></h2>
      <p class="mt-1 text-sm text-gray-600"><%= t('.description') %></p>
    </div>
  </div>

  <div class="pt-4 mt-4">
    <%= render partial: 'form', locals: {district_profile: @district_profile} %>
  </div>
</div>

app/views/buyers/district_profiles/show.html.erb
<div class="space-y-4">
  <h2 class="text-xl font-bold md:text-2xl"><%= t('.title') %></h2>

  <%= render(Buyers::DistrictProfiles::Errors::Component.new(district_profile: @district_profile, sections: [:district_information, :rfp_contact, :procurement_terms, :locations])) %>

  <div class="pt-4 mt-4">
    <%= render(Buyers::DistrictProfiles::Section::Component.new(name: t('.district_information'), description: t('.district_information_description'), path: edit_buyers_district_profile_path)) do |component| %>
      <% component.field(district_profile: @district_profile, section: :district_information, name: :district_name) %>
      <% component.field(district_profile: @district_profile, section: :district_information, name: :city) %>
      <% component.field(district_profile: @district_profile, section: :district_information, name: :county) %>
      <% component.field(district_profile: @district_profile, section: :district_information, name: :enrolled_students_number) %>
    <% end %>
  </div>

  <div class="pt-4 mt-4">
    <%= render(Buyers::DistrictProfiles::Section::Component.new(name: t('.rfp_contact'), description: t('.rfp_contact_description'), path: edit_buyers_district_profile_contact_path)) do |component| %>
      <% component.field(district_profile: @district_profile, section: :rfp_contact, name: :contact_full_name) %>
      <% component.field(district_profile: @district_profile, section: :rfp_contact, name: :contact_department_name) %>
      <% component.field(district_profile: @district_profile, section: :rfp_contact, name: :contact_title) %>
      <% component.field(district_profile: @district_profile, section: :rfp_contact, name: :contact_phone_number) %>
      <% component.field(district_profile: @district_profile, section: :rfp_contact, name: :contact_mailing_address) do %>
        <% if @district_profile.address.present? %>
          <%= @district_profile.address %>
        <% else %>
          <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800">
            <%= t('.incomplete') %>
          </span>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div class="pt-4 mt-4">
    <%= render(Buyers::DistrictProfiles::Section::Component.new(name: t('.procurement_terms'), description: t('.procurement_terms_description'), path: edit_buyers_district_profile_procurement_path)) do |component| %>
      <% component.field(district_profile: @district_profile, section: :procurement_terms, name: :local_percentage) do %>
        <%= number_to_percentage(@district_profile.local_percentage, precision: 0) %>
      <% end %>
      <% component.field(district_profile: @district_profile, section: :procurement_terms, name: :price_verified) do %>
        <% unless @district_profile.price_verified.nil? %>
          <%= @district_profile.price_verified ? t('.price_verified') : t('.price_not_verified') %>
        <% end %>
      <% end %>
      <% component.field(district_profile: @district_profile, section: :procurement_terms, name: :allow_piggyback) do %>
        <% unless @district_profile.allow_piggyback.nil? %>
          <%= @district_profile.allow_piggyback ? t('.piggyback_included') : t('.piggyback_not_included') %>
        <% end %>
      <% end %>
      <% component.field(district_profile: @district_profile, section: :procurement_terms, name: :required_insurance_per_incident) do %>
        <%= number_to_currency(@district_profile.required_insurance_per_incident, precision: 0) %>
      <% end %>
      <% component.field(district_profile: @district_profile, section: :procurement_terms, name: :required_insurance_aggregate) do %>
        <%= number_to_currency(@district_profile.required_insurance_aggregate, precision: 0) %>
      <% end %>
      <% component.field(district_profile: @district_profile, section: :procurement_terms, name: :required_insurance_automobile) do %>
        <%= number_to_currency(@district_profile.required_insurance_automobile, precision: 0) %>
      <% end %>
    <% end %>
  </div>

  <div class="pt-4 mt-4">
    <%= render(Buyers::DistrictProfiles::Section::Component.new(name: t('.locations'), description: t('.locations_description'), path: buyers_district_profile_locations_path)) do |component| %>
      <%= render(Buyers::Locations::List::Component.new(locations: @district_profile.locations.page.per(@district_profile.locations.size + 1))) %>
    <% end %>
  </div>
</div>

app/views/buyers/district_profiles/update.turbo_stream.erb
<%= turbo_stream.replace 'buyers-district-profile' do %>
  <%= render partial: 'form', locals: {district_profile: @district_profile} %>
<% end %>