config/routes.rb
Rails.application.routes.draw do
  draw(:active_storage)
  mount ActionCable.server => '/cable'

  devise_for :admin_users
  devise_for :buyers, controllers: {confirmations: 'buyers/confirmations', registrations: 'buyers/registrations'}

  namespace :admin do
    resources :admin_users
    resources :buyers, only: [:index, :show]
    resources :deliveries, only: [:show]
    resources :district_profiles, only: [:index, :show, :edit, :update]
    resources :locations, only: [:show]
    resources :procurement_types, only: [:index, :show, :new, :create, :edit, :update]
    resources :procurement_type_score_categories, only: [:show, :edit, :update, :destroy]
    resources :rfps, only: [:index, :show, :edit, :update] do
      get :download
    end

    resources :score_categories, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :score_presets, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :score_preset_values, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :scores, only: [:edit, :update, :show]

    delete :rfp_item_list_destroy, to: 'rfps#destroy_item_list'
    delete :rfp_draft_destroy, to: 'rfps#destroy_draft'
    delete :rfp_reviewed_destroy, to: 'rfps#destroy_reviewed'
    delete :rfp_final_destroy, to: 'rfps#destroy_final'

    root to: 'buyers#index'
  end

  namespace :buyers do
    resource :district_profile, only: [:show, :edit, :update, :destroy] do
      scope module: :district_profiles do
        resource :contact, only: [:edit, :update]
        resource :procurement, only: [:edit, :update]
        resources :locations, only: [:index, :show, :create, :new, :edit, :update, :destroy]
      end
    end
    resources :documents, only: [:index]
    resources :rfps, except: [:index] do
      resources :scores, except: [:new, :edit, :destroy]
      resources :score_presets, only: [:show, :update]
      resources :deliveries
      resource :item_list, only: [:edit, :update]
      resource :draft, only: [:create]
      resource :download, only: [:show]
      resource :reviewed, only: [:update]
      resource :final, only: [:update]
    end
    resource :resources, only: [:show]
    root to: 'documents#index'
  end

  resource :terms, only: [:show]

  root to: 'buyers/documents#index'
end

app/models/district_profile.rb
# == Schema Information
#
# Table name: district_profiles
#
#  id                              :bigint           not null, primary key
#  allow_piggyback                 :boolean
#  city                            :string
#  contact_department_name         :string
#  contact_full_name               :string
#  contact_mailing_address_city    :string
#  contact_mailing_address_state   :string
#  contact_mailing_address_street  :string
#  contact_mailing_address_zip     :string
#  contact_phone_number            :string
#  contact_title                   :string
#  county                          :string
#  daily_meals_number              :integer
#  district_name                   :string           not null
#  enrolled_students_number        :integer
#  local_percentage                :integer
#  price_verified                  :boolean
#  required_insurance_aggregate    :integer
#  required_insurance_automobile   :integer
#  required_insurance_per_incident :integer
#  created_at                      :datetime         not null
#  updated_at                      :datetime         not null
#  buyer_id                        :bigint           not null
#

class DistrictProfile < ApplicationRecord
  belongs_to :buyer, inverse_of: :district_profile
  delegate :locations, to: :buyer

  validates :district_name,
            :city,
            :county,
            :enrolled_students_number,
            presence: true, on: [:save, :district_information]
  validates :enrolled_students_number, numericality: {only_integer: true, allow_nil: true, greater_than: 0}, on: [:save, :district_information]

  validates :contact_phone_number, phone: {allow_blank: true}, on: [:rfp_contact]
  validates :contact_full_name,
            :contact_department_name,
            :contact_mailing_address_city,
            :contact_mailing_address_state,
            :contact_mailing_address_street,
            :contact_mailing_address_zip,
            :contact_phone_number,
            :contact_title,
            presence: true, on: [:rfp_contact]

  validates :allow_piggyback, :price_verified, inclusion: {in: [true, false], allow_blank: false}, on: [:procurement_terms]
  validates :local_percentage,
            :required_insurance_aggregate,
            :required_insurance_automobile,
            :required_insurance_per_incident,
            presence: true, on: [:procurement_terms]

  validates :locations, presence: true, on: [:locations]

  def complete?
    valid?([:district_information, :rfp_contact, :procurement_terms, :locations])
  end

  def address
    return unless contact_mailing_address_city? && contact_mailing_address_state? && contact_mailing_address_street? && contact_mailing_address_zip

    "#{contact_mailing_address_street} #{contact_mailing_address_city}, #{contact_mailing_address_state} #{contact_mailing_address_zip}"
  end
end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id             :bigint           not null, primary key
#  city           :string           not null
#  name           :string           not null
#  state          :string           not null
#  street_address :string           not null
#  zip_code       :string           not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  buyer_id       :bigint           not null
#
class Location < ApplicationRecord
  belongs_to :buyer, inverse_of: :locations

  has_one :district_profile, through: :buyer

  has_many :deliveries, inverse_of: :location, dependent: :restrict_with_error

  validates :name, :street_address, :city, :state, :zip_code, presence: true

  def name_with_address
    "#{name} (#{full_address})"
  end

  def full_address
    "#{street_address}, #{city}, #{state} #{zip_code}"
  end
end

app/controllers/admin/district_profiles_controller.rb
class Admin::DistrictProfilesController < Admin::ApplicationController
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < Admin::ApplicationController
end

app/controllers/buyers/district_profiles/contacts_controller.rb
class Buyers::DistrictProfiles::ContactsController < Buyers::ApplicationController
  before_action -> { redirect_to edit_buyers_district_profile_path }, unless: -> { current_buyer.district_profile.present? }

  def edit
    @district_profile = current_buyer.district_profile
  end

  def update
    @district_profile = current_buyer.district_profile
    respond_to do |format|
      if @district_profile.update(district_profile_params)
        if params.key?(:draft)
          @district_profile.valid?(:rfp_contact)
          flash.now[:success] = 'District Profile was successfully updated.'
          format.html { render :edit }
          format.turbo_stream { render :update }
        else
          format.any do
            flash[:success] = 'District Profile was successfully updated.'
            redirect_to edit_buyers_district_profile_procurement_path, status: :see_other
          end
        end
      else
        flash.now[:alert] = 'District Profile could not be saved.'
        format.html { render :edit }
        format.turbo_stream { render :update }
      end
    end
  end

  private

  def district_profile_params
    params.require(:district_profile).permit(:contact_full_name, :contact_mailing_address_city, :contact_department_name, :contact_full_name, :contact_mailing_address_state, :contact_mailing_address_street, :contact_mailing_address_zip, :contact_phone_number, :contact_title)
  end
end

app/controllers/buyers/district_profiles/locations_controller.rb
class Buyers::DistrictProfiles::LocationsController < Buyers::ApplicationController
  before_action -> { redirect_to edit_buyers_district_profile_path }, unless: -> { current_buyer.district_profile.present? }
  after_action :verify_authorized, except: [:index, :new, :create]

  def index
    @district_profile = current_buyer.district_profile
  end

  def new
    @location = current_buyer.locations.build
  end

  def create
    @location = current_buyer.locations.build(location_params)
    respond_to do |format|
      if @location.save
        format.any do
          flash[:success] = 'Location was successfully created.'
          redirect_to buyers_district_profile_locations_path, status: :see_other
        end
      else
        flash.now[:alert] = 'Location could not be saved.'
        format.html { render :new }
        format.turbo_stream { render :create }
      end
    end
  end

  def edit
    @location = Location.find(params[:id])
    authorize(@location)
  end

  def update
    @location = Location.find(params[:id])
    authorize(@location)
    @location.assign_attributes(location_params)
    respond_to do |format|
      if @location.save
        format.any do
          flash[:success] = 'Location was successfully updated.'
          redirect_to buyers_district_profile_locations_path, status: :see_other
        end
      else
        flash.now[:alert] = 'Location could not be saved.'
        format.html { render :edit }
        format.turbo_stream { render :update }
      end
    end
  end

  def destroy
    location = Location.find(params[:id])
    authorize(location)
    location.destroy
    redirect_to buyers_district_profile_locations_path
  end

  private

  def location_params
    params.require(:location).permit(:name, :street_address, :city, :state, :zip_code)
  end
end

app/controllers/buyers/district_profiles/procurements_controller.rb
class Buyers::DistrictProfiles::ProcurementsController < Buyers::ApplicationController
  before_action -> { redirect_to edit_buyers_district_profile_path }, unless: -> { current_buyer.district_profile.present? }

  def edit
    @district_profile = current_buyer.district_profile
  end

  def update
    @district_profile = current_buyer.district_profile
    respond_to do |format|
      if @district_profile.update(district_profile_params)
        if params.key?(:draft)
          @district_profile.valid?(:procurement_terms)
          flash.now[:success] = 'District Profile was successfully updated.'
          format.html { render :edit }
          format.turbo_stream { render :update }
        else
          format.any do
            flash[:success] = 'District Profile was successfully updated.'
            redirect_to buyers_district_profile_locations_path, status: :see_other
          end
        end
      else
        flash.now[:alert] = 'District Profile could not be saved.'
        format.html { render :edit }
        format.turbo_stream { render :update }
      end
    end
  end

  private

  def district_profile_params
    params.require(:district_profile).permit(:local_percentage, :price_verified, :allow_piggyback, :required_insurance_aggregate, :required_insurance_automobile, :required_insurance_per_incident)
  end
end

app/controllers/buyers/district_profiles_controller.rb
class Buyers::DistrictProfilesController < Buyers::ApplicationController
  before_action -> { redirect_to edit_buyers_district_profile_path }, if: -> { current_buyer.district_profile.blank? }, only: [:show]

  def show
    @district_profile = current_buyer.district_profile || current_buyer.build_district_profile
  end

  def edit
    @district_profile = current_buyer.district_profile || current_buyer.build_district_profile
  end

  def update
    @district_profile = current_buyer.district_profile || current_buyer.build_district_profile
    respond_to do |format|
      if @district_profile.update(district_profile_params)
        if params.key?(:draft)
          @district_profile.valid?(:district_information)
          format.html { render :edit }
          format.turbo_stream { render :update }
        else
          format.any do
            flash[:success] = 'District Profile was successfully updated.'
            redirect_to edit_buyers_district_profile_contact_path, status: :see_other
          end
        end
      else
        flash[:alert] = 'District Profile could not be saved.'
        format.html { render :edit }
        format.turbo_stream { render :update }
      end
    end
  end

  private

  def district_profile_params
    params.require(:district_profile).permit(:district_name, :city, :county, :enrolled_students_number)
  end
end

app/views/buyers/district_profiles/locations/_form.html.erb
<%= turbo_frame_tag 'buyers-district-profile-location' do %>
  <%= form_for [:buyers, :district_profile, location], as: :location, html: {data: {turbo_frame: '_top', controller: 'autoplaces', action: 'google-maps-callback@window->autoplaces#initAutocomplete', autoplaces_country_value: ['us']}} do |f| %>
    <div class="divide-y divide-gray-200">
      <div class="space-y-4">
        <div class="grid grid-cols-1 gap-y-4 gap-x-4 sm:grid-cols-6">
          <div class="sm:col-span-4">
            <%= f.label :name %>
            <%= f.text_field :name, required: true %>
          </div>
        </div>

        <div class="grid grid-cols-1 gap-y-4 gap-x-4 sm:grid-cols-6">
          <div class="sm:col-span-6">
            <%= f.label :street_address %>
            <%= f.text_field :street_address, required: true, data: {action: 'keydown->autoplaces#preventSubmit', autoplaces_target: 'address'} %>
          </div>

          <div class="sm:col-span-2">
            <%= f.label :city %>
            <%= f.text_field :city, data: {autoplaces_target: 'city'} %>
          </div>

          <div class="sm:col-span-2">
            <%= f.label :state %>
            <%= f.text_field :state, data: {autoplaces_target: 'state'} %>
          </div>

          <div class="sm:col-span-2">
            <%= f.label :zip_code %>
            <%= f.text_field :zip_code, data: {autoplaces_target: 'postalCode'} %>
          </div>
        </div>
      </div>

      <div class="pt-4 mt-4">
        <div class="flex justify-start space-x-4">
          <%= f.button t('.submit'), class: 'forms-submit' %>
          <%= link_to t('.cancel'), buyers_district_profile_locations_path, data: {turbo_frame: '_top'}, class: 'forms-submit--outline' %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/buyers/district_profiles/locations/create.turbo_stream.erb
<%= turbo_stream.replace 'buyers-district-profile-location' do %>
  <%= render partial: 'form', locals: {location: @location} %>
<% end %>

app/views/buyers/district_profiles/locations/edit.html.erb
<div class="divide-y divide-gray-200">
  <div class="space-y-8">
    <%= render(Buyers::Steps::Component.new(title: DistrictProfile.model_name.human)) do |component| %>
      <%= component.step index: 1, current_index: 4, section: t(:district_information, scope: [:activerecord, :attributes, :district_profile]), path: edit_buyers_district_profile_path, valid: @location.district_profile.valid?(:district_information) %>
      <%= component.step index: 2, current_index: 4, section: t(:rfp_contact, scope: [:activerecord, :attributes, :district_profile]), path: edit_buyers_district_profile_contact_path, valid: @location.district_profile.valid?(:rfp_contact) %>
      <%= component.step index: 3, current_index: 4, section: t(:procurement_terms, scope: [:activerecord, :attributes, :district_profile]), path: edit_buyers_district_profile_procurement_path, valid: @location.district_profile.valid?(:procurement_terms) %>
      <%= component.step index: 4, current_index: 4, section: t(:locations, scope: [:activerecord, :attributes, :district_profile]), path: buyers_district_profile_locations_path, valid: @location.district_profile.valid?(:locations) %>
    <% end %>

    <div>
      <h2 class="text-lg leading-6 font-medium text-gray-900"><%= t('.title', name: @location.name) %></h2>
    </div>
  </div>

  <div class="pt-4 mt-4">
    <%= render partial: 'form', locals: {location: @location} %>
  </div>
</div>

app/views/buyers/district_profiles/locations/index.html.erb
<div class="divide-y divide-gray-200">
  <div class="space-y-8">
    <%= render(Buyers::Steps::Component.new(title: DistrictProfile.model_name.human)) do |component| %>
      <%= component.step index: 1, current_index: 4, section: t(:district_information, scope: [:activerecord, :attributes, :district_profile]), path: edit_buyers_district_profile_path, valid: @district_profile.valid?(:district_information) %>
      <%= component.step index: 2, current_index: 4, section: t(:rfp_contact, scope: [:activerecord, :attributes, :district_profile]), path: edit_buyers_district_profile_contact_path, valid: @district_profile.valid?(:rfp_contact) %>
      <%= component.step index: 3, current_index: 4, section: t(:procurement_terms, scope: [:activerecord, :attributes, :district_profile]), path: edit_buyers_district_profile_procurement_path, valid: @district_profile.valid?(:procurement_terms) %>
      <%= component.step index: 4, current_index: 4, section: t(:locations, scope: [:activerecord, :attributes, :district_profile]), path: buyers_district_profile_locations_path, valid: @district_profile.valid?(:locations) %>
    <% end %>

    <div>
      <h2 class="text-lg leading-6 font-medium text-gray-900"><%= t('.title') %></h2>
      <p class="mt-1 text-sm text-gray-600"><%= t('.description') %></p>
    </div>
  </div>

  <div class="pt-4 mt-4">
    <% if @district_profile.locations.exists? %>
      <%= render(Buyers::Locations::List::Component.new(locations: @district_profile.locations.page(params.fetch(:page, 1)))) %>

      <div class="mt-4 md:space-y-0 md:flex md:items-center">
        <%= link_to new_buyers_district_profile_location_path, class: 'inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-cyan-700 hover:bg-cyan-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-cyan-500' do %>
          <%= inline_svg_tag 'buyers/locations/plus.svg', class: '-ml-1 mr-2 h-5 w-5', aria_hidden: true %>
          <span><%= t('.new') %></span>
        <% end %>
      </div>
    <% else %>
      <%= render(Buyers::Locations::Empty::Component.new) %>
    <% end %>
  </div>

  <div class="pt-4 mt-4">
    <%= link_to t('.review'), buyers_district_profile_path, class: 'forms-submit' %>
  </div>
</div>

app/views/buyers/district_profiles/locations/new.html.erb
<div class="divide-y divide-gray-200">
  <div class="space-y-8">
    <%= render(Buyers::Steps::Component.new(title: DistrictProfile.model_name.human)) do |component| %>
      <%= component.step index: 1, current_index: 4, section: t(:district_information, scope: [:activerecord, :attributes, :district_profile]), path: edit_buyers_district_profile_path, valid: @location.district_profile.valid?(:district_information) %>
      <%= component.step index: 2, current_index: 4, section: t(:rfp_contact, scope: [:activerecord, :attributes, :district_profile]), path: edit_buyers_district_profile_contact_path, valid: @location.district_profile.valid?(:rfp_contact) %>
      <%= component.step index: 3, current_index: 4, section: t(:procurement_terms, scope: [:activerecord, :attributes, :district_profile]), path: edit_buyers_district_profile_procurement_path, valid: @location.district_profile.valid?(:procurement_terms) %>
      <%= component.step index: 4, current_index: 4, section: t(:locations, scope: [:activerecord, :attributes, :district_profile]), path: buyers_district_profile_locations_path, valid: @location.district_profile.valid?(:locations) %>
    <% end %>

    <div>
      <h2 class="text-lg leading-6 font-medium text-gray-900"><%= t('.title') %></h2>
    </div>
  </div>

  <div class="pt-4 mt-4">
    <%= render partial: 'form', locals: {location: @location} %>
  </div>
</div>

app/views/buyers/district_profiles/locations/update.turbo_stream.erb
<%= turbo_stream.replace 'buyers-district-profile-location' do %>
  <%= render partial: 'form', locals: {location: @location} %>
<% end %>