config/routes.rb
Rails.application.routes.draw do
  draw(:active_storage)
  mount ActionCable.server => '/cable'

  devise_for :admin_users
  devise_for :buyers, controllers: {confirmations: 'buyers/confirmations', registrations: 'buyers/registrations'}

  namespace :admin do
    resources :admin_users
    resources :buyers, only: [:index, :show]
    resources :deliveries, only: [:show]
    resources :district_profiles, only: [:index, :show, :edit, :update]
    resources :locations, only: [:show]
    resources :procurement_types, only: [:index, :show, :new, :create, :edit, :update]
    resources :procurement_type_score_categories, only: [:show, :edit, :update, :destroy]
    resources :rfps, only: [:index, :show, :edit, :update] do
      get :download
    end

    resources :score_categories, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :score_presets, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :score_preset_values, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :scores, only: [:edit, :update, :show]

    delete :rfp_item_list_destroy, to: 'rfps#destroy_item_list'
    delete :rfp_draft_destroy, to: 'rfps#destroy_draft'
    delete :rfp_reviewed_destroy, to: 'rfps#destroy_reviewed'
    delete :rfp_final_destroy, to: 'rfps#destroy_final'

    root to: 'buyers#index'
  end

  namespace :buyers do
    resource :district_profile, only: [:show, :edit, :update, :destroy] do
      scope module: :district_profiles do
        resource :contact, only: [:edit, :update]
        resource :procurement, only: [:edit, :update]
        resources :locations, only: [:index, :show, :create, :new, :edit, :update, :destroy]
      end
    end
    resources :documents, only: [:index]
    resources :rfps, except: [:index] do
      resources :scores, except: [:new, :edit, :destroy]
      resources :score_presets, only: [:show, :update]
      resources :deliveries
      resource :item_list, only: [:edit, :update]
      resource :draft, only: [:create]
      resource :download, only: [:show]
      resource :reviewed, only: [:update]
      resource :final, only: [:update]
    end
    resource :resources, only: [:show]
    root to: 'documents#index'
  end

  resource :terms, only: [:show]

  root to: 'buyers/documents#index'
end

app/models/buyer.rb
# == Schema Information
#
# Table name: buyers
#
#  id                     :bigint           not null, primary key
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  full_name              :string           not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  unconfirmed_email      :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class Buyer < ApplicationRecord
  devise :database_authenticatable, :confirmable, :registerable, :recoverable, :rememberable, :validatable

  validates :terms_and_conditions, acceptance: true

  has_one :district_profile, inverse_of: :buyer, dependent: :destroy
  has_many :rfps, inverse_of: :buyer, dependent: :destroy
  has_many :locations, inverse_of: :buyer, dependent: :destroy

  delegate :district_name, to: :district_profile, allow_nil: true

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end
end

app/controllers/admin/buyers_controller.rb
class Admin::BuyersController < Admin::ApplicationController
  def scoped_resource
    Buyer.where.not(confirmed_at: nil)
  end
end

app/controllers/admin/rfps_controller.rb
class Admin::RfpsController < Admin::ApplicationController
  def destroy_item_list
    requested_resource.item_list.purge
    redirect_back(fallback_location: requested_resource)
  end

  def download
    rfp = Rfp.find(params[:rfp_id])
    ::RfpCompositor.new(rfp).create do |download|
      send_data download.read, filename: "DRAFT_RFP_#{Time.current.to_fs(:number)}.docx"
    end
  end

  def destroy_draft
    requested_resource.draft.purge
    redirect_back(fallback_location: requested_resource)
  end

  def destroy_reviewed
    requested_resource.reviewed.purge
    redirect_back(fallback_location: requested_resource)
  end

  def destroy_final
    requested_resource.final.purge
    redirect_back(fallback_location: requested_resource)
  end

  def default_sorting_attribute
    :updated_at
  end

  def default_sorting_direction
    :desc
  end
end

app/controllers/buyers/application_controller.rb
class Buyers::ApplicationController < ApplicationController
  include Pundit::Authorization

  before_action :authenticate_buyer!, unless: :devise_controller?
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def pundit_user = current_buyer

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(request.referer || root_path)
  end
end

app/controllers/buyers/confirmations_controller.rb
class Buyers::ConfirmationsController < Devise::ConfirmationsController
  def show
    super do |buyer|
      AdminNotificationMailer.new_registration(resource).deliver if buyer.confirmed?
    end
  end
end

app/controllers/buyers/deliveries_controller.rb
class Buyers::DeliveriesController < Buyers::ApplicationController
  after_action :verify_authorized

  def index
    authorize(current_rfp, :edit?)
    @rfp = current_rfp
  end

  def new
    authorize(current_rfp, :edit?)
    @delivery = current_rfp.deliveries.build(window_start_time: 4, window_end_time: 5)
  end

  def edit
    authorize(current_rfp, :edit?)
    @delivery = current_rfp.deliveries.find(params[:id])
  end

  def create
    authorize(current_rfp, :edit?)
    @delivery = current_rfp.deliveries.build(delivery_params)
    respond_to do |format|
      if @delivery.save
        format.any do
          flash[:success] = 'Schedule was successfully created.'
          redirect_to buyers_rfp_deliveries_path(current_rfp), status: :see_other
        end
      else
        flash.now[:alert] = 'Schedule could not be saved.'
        format.html { render :new }
        format.turbo_stream { render :create }
      end
    end
  end

  def update
    authorize(current_rfp, :edit?)
    @delivery = current_rfp.deliveries.find(params[:id])
    respond_to do |format|
      if @delivery.update(delivery_params)
        format.any do
          flash[:success] = 'Schedule was successfully updated.'
          redirect_to buyers_rfp_deliveries_path(current_rfp), status: :see_other
        end
      else
        flash.now[:alert] = 'Schedule could not be saved.'
        format.html { render :edit }
        format.turbo_stream { render :update }
      end
    end
  end

  def destroy
    authorize(current_rfp, :edit?)
    schedule = current_rfp.deliveries.find(params[:id])
    schedule.destroy
    redirect_to buyers_rfp_deliveries_path(current_rfp)
  end

  private

  def delivery_params
    unprocessed_params.merge(delivery_days: unprocessed_params.fetch(:delivery_days, []).reject(&:blank?))
  end

  def unprocessed_params
    params.require(:delivery).permit(:location_id, :deliveries_per_week, :window_start_time, :window_end_time, delivery_days: [])
  end

  def current_rfp
    @current_rfp ||= Rfp.find(params[:rfp_id])
  end
end

app/controllers/buyers/district_profiles/contacts_controller.rb
class Buyers::DistrictProfiles::ContactsController < Buyers::ApplicationController
  before_action -> { redirect_to edit_buyers_district_profile_path }, unless: -> { current_buyer.district_profile.present? }

  def edit
    @district_profile = current_buyer.district_profile
  end

  def update
    @district_profile = current_buyer.district_profile
    respond_to do |format|
      if @district_profile.update(district_profile_params)
        if params.key?(:draft)
          @district_profile.valid?(:rfp_contact)
          flash.now[:success] = 'District Profile was successfully updated.'
          format.html { render :edit }
          format.turbo_stream { render :update }
        else
          format.any do
            flash[:success] = 'District Profile was successfully updated.'
            redirect_to edit_buyers_district_profile_procurement_path, status: :see_other
          end
        end
      else
        flash.now[:alert] = 'District Profile could not be saved.'
        format.html { render :edit }
        format.turbo_stream { render :update }
      end
    end
  end

  private

  def district_profile_params
    params.require(:district_profile).permit(:contact_full_name, :contact_mailing_address_city, :contact_department_name, :contact_full_name, :contact_mailing_address_state, :contact_mailing_address_street, :contact_mailing_address_zip, :contact_phone_number, :contact_title)
  end
end

app/controllers/buyers/district_profiles/locations_controller.rb
class Buyers::DistrictProfiles::LocationsController < Buyers::ApplicationController
  before_action -> { redirect_to edit_buyers_district_profile_path }, unless: -> { current_buyer.district_profile.present? }
  after_action :verify_authorized, except: [:index, :new, :create]

  def index
    @district_profile = current_buyer.district_profile
  end

  def new
    @location = current_buyer.locations.build
  end

  def create
    @location = current_buyer.locations.build(location_params)
    respond_to do |format|
      if @location.save
        format.any do
          flash[:success] = 'Location was successfully created.'
          redirect_to buyers_district_profile_locations_path, status: :see_other
        end
      else
        flash.now[:alert] = 'Location could not be saved.'
        format.html { render :new }
        format.turbo_stream { render :create }
      end
    end
  end

  def edit
    @location = Location.find(params[:id])
    authorize(@location)
  end

  def update
    @location = Location.find(params[:id])
    authorize(@location)
    @location.assign_attributes(location_params)
    respond_to do |format|
      if @location.save
        format.any do
          flash[:success] = 'Location was successfully updated.'
          redirect_to buyers_district_profile_locations_path, status: :see_other
        end
      else
        flash.now[:alert] = 'Location could not be saved.'
        format.html { render :edit }
        format.turbo_stream { render :update }
      end
    end
  end

  def destroy
    location = Location.find(params[:id])
    authorize(location)
    location.destroy
    redirect_to buyers_district_profile_locations_path
  end

  private

  def location_params
    params.require(:location).permit(:name, :street_address, :city, :state, :zip_code)
  end
end

app/controllers/buyers/district_profiles/procurements_controller.rb
class Buyers::DistrictProfiles::ProcurementsController < Buyers::ApplicationController
  before_action -> { redirect_to edit_buyers_district_profile_path }, unless: -> { current_buyer.district_profile.present? }

  def edit
    @district_profile = current_buyer.district_profile
  end

  def update
    @district_profile = current_buyer.district_profile
    respond_to do |format|
      if @district_profile.update(district_profile_params)
        if params.key?(:draft)
          @district_profile.valid?(:procurement_terms)
          flash.now[:success] = 'District Profile was successfully updated.'
          format.html { render :edit }
          format.turbo_stream { render :update }
        else
          format.any do
            flash[:success] = 'District Profile was successfully updated.'
            redirect_to buyers_district_profile_locations_path, status: :see_other
          end
        end
      else
        flash.now[:alert] = 'District Profile could not be saved.'
        format.html { render :edit }
        format.turbo_stream { render :update }
      end
    end
  end

  private

  def district_profile_params
    params.require(:district_profile).permit(:local_percentage, :price_verified, :allow_piggyback, :required_insurance_aggregate, :required_insurance_automobile, :required_insurance_per_incident)
  end
end

app/controllers/buyers/district_profiles_controller.rb
class Buyers::DistrictProfilesController < Buyers::ApplicationController
  before_action -> { redirect_to edit_buyers_district_profile_path }, if: -> { current_buyer.district_profile.blank? }, only: [:show]

  def show
    @district_profile = current_buyer.district_profile || current_buyer.build_district_profile
  end

  def edit
    @district_profile = current_buyer.district_profile || current_buyer.build_district_profile
  end

  def update
    @district_profile = current_buyer.district_profile || current_buyer.build_district_profile
    respond_to do |format|
      if @district_profile.update(district_profile_params)
        if params.key?(:draft)
          @district_profile.valid?(:district_information)
          format.html { render :edit }
          format.turbo_stream { render :update }
        else
          format.any do
            flash[:success] = 'District Profile was successfully updated.'
            redirect_to edit_buyers_district_profile_contact_path, status: :see_other
          end
        end
      else
        flash[:alert] = 'District Profile could not be saved.'
        format.html { render :edit }
        format.turbo_stream { render :update }
      end
    end
  end

  private

  def district_profile_params
    params.require(:district_profile).permit(:district_name, :city, :county, :enrolled_students_number)
  end
end

app/controllers/buyers/documents_controller.rb
class Buyers::DocumentsController < Buyers::ApplicationController
  def index
    flash.now[:warning] = t('.complete_your_profile_html', complete_link: view_context.link_to(t('.complete_link_html'), edit_buyers_district_profile_path, class: 'flash__link')).html_safe unless current_buyer.district_profile&.complete?
    @documents = current_buyer.rfps.order(updated_at: :desc).page(params[:page] || 1).per(params[:per_page] || Kaminari.config.default_per_page)
  end
end

app/controllers/buyers/downloads_controller.rb
class Buyers::DownloadsController < Buyers::ApplicationController
  after_action :verify_authorized

  def show
    authorize(current_rfp)
    ::RfpCompositor.new(current_rfp).create do |download|
      send_data download.read, filename: "DRAFT_RFP_#{Time.current.to_fs(:number)}.docx"
    end
  end

  private

  def current_rfp
    @current_rfp ||= Rfp.find(params[:rfp_id])
  end
end

app/controllers/buyers/drafts_controller.rb
class Buyers::DraftsController < Buyers::ApplicationController
  after_action :verify_authorized

  def create
    authorize(current_rfp)
    if ::RfpCompositor.new(current_rfp).attach
      flash[:success] = 'Draft RFP was successfully created.'
    else
      flash[:alert] = 'There was a problem creating the RFP.'
    end
    redirect_to buyers_rfp_path(current_rfp)
  end

  private

  def current_rfp
    @current_rfp ||= Rfp.find(params[:rfp_id])
  end
end

app/controllers/buyers/finals_controller.rb
class Buyers::FinalsController < Buyers::ApplicationController
  after_action :verify_authorized

  def update
    @rfp ||= Rfp.find(params[:rfp_id])
    authorize(@rfp)
    @rfp.final.attach(item_list_params[:final])
    redirect_to buyers_rfp_path(@rfp)
  end

  private

  def item_list_params
    params.require(:rfp).permit(:final)
  end
end

app/controllers/buyers/item_lists_controller.rb
class Buyers::ItemListsController < Buyers::ApplicationController
  after_action :verify_authorized

  def edit
    @rfp = Rfp.find(params[:rfp_id])
    authorize(@rfp)
  end

  def update
    @rfp = Rfp.find(params[:rfp_id])
    authorize(@rfp)
    respond_to do |format|
      if @rfp.item_list.attach(item_list_params[:item_list])
        flash.now[:success] = 'District Profile was successfully updated.'
      else
        flash.now[:alert] = 'District Profile could not be saved.'
      end
      format.html { render :edit }
      format.turbo_stream { render :update }
    end
  end

  private

  def item_list_params
    params.require(:rfp).permit(:item_list)
  end
end

app/controllers/buyers/registrations_controller.rb
class Buyers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:full_name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:full_name, :email, :password, :current_password)
    end
  end

  def after_sign_up_path_for(_resource)
    new_buyer_session_path if is_navigational_format?
  end

  def after_inactive_sign_up_path_for(_resource)
    new_buyer_session_path
  end
end

app/controllers/buyers/resources_controller.rb
class Buyers::ResourcesController < Buyers::ApplicationController
  skip_before_action :authenticate_buyer!

  def show
    redirect_to Rails.application.config.external_resources_link, allow_other_host: true
  end
end

app/controllers/buyers/revieweds_controller.rb
class Buyers::ReviewedsController < Buyers::ApplicationController
  after_action :verify_authorized

  def update
    @rfp ||= Rfp.find(params[:rfp_id])
    authorize(@rfp)
    @rfp.reviewed.attach(item_list_params[:reviewed])
    redirect_to buyers_rfp_path(@rfp)
  end

  private

  def item_list_params
    params.require(:rfp).permit(:reviewed)
  end
end

app/views/buyers/rfps/_display_field.erb
<tr>
  <td class="buyers__display-field-label <%=@rfp.errors[attribute].present? ? 'buyers__display-field-label--error' : ''%>">
    <%= Rfp.human_attribute_name(attribute) %>
  </td>
  <td>
    <%= local_assigns.fetch :display_value, @rfp.send(attribute) %>
    <%= render 'incomplete' if @rfp.errors[attribute].present?%>
  </td>
</tr>

app/views/buyers/rfps/_form.html.erb
<%= turbo_frame_tag 'buyers-rfp' do %>
  <%= form_for [:buyers, proposal], as: :rfp, html: {data: {turbo_frame: '_top'}} do |f| %>
    <div class="divide-y divide-gray-200">
      <div class="space-y-4">
        <div class="grid grid-cols-1 gap-y-4 gap-x-4 sm:grid-cols-6">
          <div class="sm:col-span-3">
            <%= f.label :start_year %>
            <%= f.select :start_year, (1.hour.from_now.year..5.years.from_now.year).map { |year| ["#{year} - #{year+1}", year] }, {} %>
          </div>
        </div>
        <div class="grid grid-cols-1 gap-y-4 gap-x-4 sm:grid-cols-6">
          <div class="sm:col-span-3">
            <%= f.label :procurement_type_id %>
            <%= f.select :procurement_type_id, ProcurementType.published.map { |w| [w.name, w.id] }, {} %>
          </div>
        </div>
      </div>

      <div class="pt-4 mt-8">
        <div class="flex justify-start space-x-4">
          <%= f.button 'Next', class: 'forms-submit' %>
          <%= f.button 'Save draft', class: 'forms-submit--outline', name: :draft, value: true %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/buyers/rfps/create.turbo_stream.erb
<%= turbo_stream.replace 'buyers-rfp' do %>
  <%= render partial: 'form', locals: {proposal: @rfp} %>
<% end %>

app/views/buyers/rfps/edit.html.erb
<div class="divide-y divide-gray-200">
  <div class="space-y-8">
    <%= render(Buyers::Steps::Component.new(title: Rfp.model_name.human)) do |component| %>
      <%= component.step index: 1, current_index: 1, section: t(:purpose, scope: [:activerecord, :attributes, :rfp]), path: edit_buyers_rfp_path(@rfp), valid: @rfp.valid?(:purpose) %>
      <%= component.step index: 2, current_index: 1, section: t(:scores, scope: [:activerecord, :attributes, :rfp]), path: buyers_rfp_scores_path(@rfp), valid: @rfp.valid?(:scores) %>
      <%= component.step index: 3, current_index: 1, section: t(:deliveries, scope: [:activerecord, :attributes, :rfp]), path: buyers_rfp_deliveries_path(@rfp), valid: @rfp.valid?(:deliveries) %>
      <%= component.step index: 4, current_index: 1, section: t(:item_list, scope: [:activerecord, :attributes, :rfp]), path: edit_buyers_rfp_item_list_path(@rfp), valid: @rfp.item_list.present? %>
    <% end %>

    <div>
      <h2 class="text-lg leading-6 font-medium text-gray-900"><%= t('.title') %></h2>
      <p class="mt-1 text-sm text-gray-600"><%= t('.description_html', mail_link: mail_to(Rails.application.config.support_email, Rails.application.config.support_email, class: 'text-cyan-700 font-medium underline hover:text-cyan-600')) %></p>
    </div>
  </div>

  <div class="pt-4 mt-4">
    <%= render partial: 'form', locals: {proposal: @rfp} %>
  </div>
</div>

app/views/buyers/rfps/new.html.erb
<div class="divide-y divide-gray-200">
  <div class="space-y-8">
    <%= render(Buyers::Steps::Component.new(title: Rfp.model_name.human)) do |component| %>
      <%= component.step index: 1, current_index: 1, section: t(:purpose, scope: [:activerecord, :attributes, :rfp]), path: '#', valid: true %>
      <%= component.step index: 2, current_index: 1, section: t(:scores, scope: [:activerecord, :attributes, :rfp]), path: '#', valid: true %>
      <%= component.step index: 3, current_index: 1, section: t(:deliveries, scope: [:activerecord, :attributes, :rfp]), path: '#', valid: true %>
      <%= component.step index: 4, current_index: 1, section: t(:item_list, scope: [:activerecord, :attributes, :rfp]), path: '#', valid: true %>
    <% end %>

    <div>
      <h2 class="text-lg leading-6 font-medium text-gray-900"><%= t('.title') %></h2>
      <p class="mt-1 text-sm text-gray-600"><%= t('.description_html', mail_link: mail_to(Rails.application.config.support_email, Rails.application.config.support_email, class: 'text-cyan-700 font-medium underline hover:text-cyan-600')) %></p>
    </div>
  </div>

  <div class="pt-4 mt-4">
    <%= render partial: 'form', locals: {proposal: @rfp} %>
  </div>
</div>

app/views/buyers/rfps/show.html.erb
<div class="space-y-4">
  <h2 class="text-xl font-bold md:text-2xl"><%= t('.title') %></h2>

  <%= render(Buyers::Proposals::Download::Component.new(proposal: @rfp)) %>

  <%= render(Buyers::DistrictProfiles::Errors::Component.new(district_profile: @rfp.district_profile, sections: [:district_information, :rfp_contact, :procurement_terms])) %>
  <%= render(Buyers::Proposals::Errors::Component.new(proposal: @rfp, sections: [:rfp_purpose, :scores, :deliveries, :item_list])) %>

  <div class="pt-4 mt-4 bg-white space-y-2 rounded-lg p-6 shadow">
    <h3 class="text-lg leading-6 font-medium text-gray-900">Interested in finding qualified local producers to bid on your RFP?</h3>
    <p class="text-sm text-gray-600">
      SupplyChange has created a Local and Sustainable Supplier Guide that you can send to local vendors to support them with the application process. You can find that document in the Resources Folder in the Menu. Learn more about SupplyChange’s work to bridge the gap between local and sustainable producers and institutions at supplychange.co.
    </p>
    <p><a class='text-sm text-indigo-500' href='https://supplychange.co'>Visit SupplyChange.co →</a></p>
  </div>

  <div class="pt-4 mt-4">
    <%= render(Buyers::Proposals::Section::Component.new(name: t('.rfp_purpose'), description: t('.rfp_purpose_description'), path: edit_buyers_rfp_path(@rfp))) do |component| %>
      <% component.field(proposal: @rfp, section: :rfp_purpose, name: :procurement_type) do %>
        <%= @rfp.procurement_type_name %>
      <% end %>
      <% component.field(proposal: @rfp, section: :rfp_purpose, name: :start_year) do %>
        <%= @rfp.school_year %>
      <% end %>
    <% end %>
  </div>

  <div class="pt-4 mt-4">
    <%= render(Buyers::DistrictProfiles::Section::Component.new(name: t(:district_information, scope: [:buyers, :district_profiles, :show]), description: t(:district_information_description, scope: [:buyers, :district_profiles, :show]), path: edit_buyers_district_profile_path)) do |component| %>
      <% component.field(district_profile: @rfp.district_profile, section: :district_information, name: :district_name) %>
      <% component.field(district_profile: @rfp.district_profile, section: :district_information, name: :city) %>
      <% component.field(district_profile: @rfp.district_profile, section: :district_information, name: :county) %>
      <% component.field(district_profile: @rfp.district_profile, section: :district_information, name: :enrolled_students_number) %>
    <% end %>
  </div>

  <div class="pt-4 mt-4">
    <%= render(Buyers::DistrictProfiles::Section::Component.new(name: t(:rfp_contact, scope: [:buyers, :district_profiles, :show]), description: t(:rfp_contact_description, scope: [:buyers, :district_profiles, :show]), path: edit_buyers_district_profile_contact_path)) do |component| %>
      <% component.field(district_profile: @rfp.district_profile, section: :rfp_contact, name: :contact_full_name) %>
      <% component.field(district_profile: @rfp.district_profile, section: :rfp_contact, name: :contact_department_name) %>
      <% component.field(district_profile: @rfp.district_profile, section: :rfp_contact, name: :contact_title) %>
      <% component.field(district_profile: @rfp.district_profile, section: :rfp_contact, name: :contact_phone_number) %>
      <% component.field(district_profile: @rfp.district_profile, section: :rfp_contact, name: :contact_mailing_address) do %>
        <% if @rfp.district_profile.address.present? %>
          <%= @rfp.district_profile.address %>
        <% else %>
          <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800">
            <%= t('.incomplete') %>
          </span>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div class="pt-4 mt-4">
    <%= render(Buyers::DistrictProfiles::Section::Component.new(name: t(:procurement_terms, scope: [:buyers, :district_profiles, :show]), description: t(:procurement_terms_description, scope: [:buyers, :district_profiles, :show]), path: edit_buyers_district_profile_procurement_path)) do |component| %>
      <% component.field(district_profile: @rfp.district_profile, section: :procurement_terms, name: :local_percentage) do %>
        <%= number_to_percentage(@rfp.district_profile.local_percentage, precision: 0) %>
      <% end %>
      <% component.field(district_profile: @rfp.district_profile, section: :procurement_terms, name: :price_verified) do %>
        <% unless @rfp.district_profile.price_verified.nil? %>
          <%= @rfp.district_profile.price_verified ? t('.price_verified') : t('.price_not_verified') %>
        <% end %>
      <% end %>
      <% component.field(district_profile: @rfp.district_profile, section: :procurement_terms, name: :allow_piggyback) do %>
        <% unless @rfp.district_profile.allow_piggyback.nil? %>
          <%= @rfp.district_profile.allow_piggyback ? t('.piggyback_included') : t('.piggyback_not_included') %>
        <% end %>
      <% end %>
      <% component.field(district_profile: @rfp.district_profile, section: :procurement_terms, name: :required_insurance_per_incident) do %>
        <%= number_to_currency(@rfp.district_profile.required_insurance_per_incident, precision: 0) %>
      <% end %>
      <% component.field(district_profile: @rfp.district_profile, section: :procurement_terms, name: :required_insurance_aggregate) do %>
        <%= number_to_currency(@rfp.district_profile.required_insurance_aggregate, precision: 0) %>
      <% end %>
      <% component.field(district_profile: @rfp.district_profile, section: :procurement_terms, name: :required_insurance_automobile) do %>
        <%= number_to_currency(@rfp.district_profile.required_insurance_automobile, precision: 0) %>
      <% end %>
    <% end %>
  </div>

  <div class="pt-4 mt-4">
    <%= render(Buyers::Scores::Component.new(name: t('.scores'), description: t('.scores_description'), path: buyers_rfp_scores_path(@rfp))) do |component| %>
      <% @rfp.scores.each do |score| %>
        <% component.category(name: score.score_category.name, value: score.value) %>
      <% end %>
    <% end %>
  </div>

  <div class="pt-4 mt-4">
    <%= render(Buyers::Proposals::Section::Component.new(name: t('.deliveries'), description: t('.deliveries_description'), path: buyers_rfp_deliveries_path(@rfp))) do |component| %>
      <%= render(Buyers::Deliveries::List::Component.new(deliveries: @rfp.deliveries.page.per(@rfp.deliveries.size + 1))) %>
    <% end %>
  </div>

  <div class="pt-4 mt-4">
    <%= render(Buyers::Proposals::Section::Component.new(name: t('.item_list'), path: edit_buyers_rfp_item_list_path(@rfp))) do |component| %>
      <% if @rfp.item_list.attached? %>
        <ul role="list" class="border border-gray-200 rounded-md divide-y divide-gray-200">
          <li role="listitem" class="pl-3 pr-4 py-3 flex items-center justify-between text-sm group">
            <div class="w-0 flex-1 flex items-center">
              <%= inline_svg_tag 'buyers/item_lists/attachment.svg', class: 'flex-shrink-0 h-5 w-5 text-gray-400', aria_hidden: true %>
              <span class="ml-2 flex-1 w-0 truncate">
                <%= @rfp.item_list.filename %>
                <span class="text-gray-600 ml-2"><%= l(@rfp.item_list.created_at, format: :long) %></span>
              </span>
            </div>
            <%= link_to t('.download'), rails_blob_path(@rfp.item_list, disposition: 'attachment'), class: 'block ml-4 flex-shrink-0 text-medium text-cyan-700 hover:text-cyan-500' %>
          </li>
        </ul>
      <% end %>
    <% end %>
  </div>
</div>

app/views/buyers/rfps/update.turbo_stream.erb
<%= turbo_stream.replace 'buyers-rfp' do %>
  <%= render partial: 'form', locals: {proposal: @rfp} %>
<% end %>